# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      # Set up mock mode for documentation builds
      - echo "SVF_MOCK_MODE=1" >> $READTHEDOCS_VIRTUALENV_PATH/bin/activate
    post_install:
      # Ensure mock mode is available during doc generation
      - export SVF_MOCK_MODE=1

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Allow warnings for mock imports
  builder: html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - dev  # Include development dependencies for mock support
    - requirements: docs/requirements.txt
  system_packages: false

# Build formats
formats:
  - pdf
  - epub
  - htmlzip

# Search configuration
search:
  ranking:
    api/*: 2
    tutorials/*: 3
    guides/*: 1
    examples/*: 1

# Subprojects for versioning
subprojects:
  include:
    - usb4-api
    - mock-testing
    - reporting-system