# .readthedocs.yaml
# ReadTheDocs configuration for SerDes Validation Framework
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - export SVF_MOCK_MODE=1

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

formats:
  - htmlzip